FROM openjdk:8-jdk-alpine
MAINTAINER Rriz
EXPOSE 8761
ADD target/treeflex-service-discovery-server-0.0.1-SNAPSHOT.jar treeflex-service-discovery-server-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "treeflex-service-discovery-server-0.0.1-SNAPSHOT.jar"]
