spring:
  application:
    name: treeflex-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/rzdp/treeflexcore-config.git
          search-paths:
            - test-service
          username: ${GIT_USERNAME}
          password: ${GIT_PASSWORD}
  profiles:
    active: default
server:
  port: 8888