spring:
  application:
    name: treeflex-config-server
  cloud:
    config:
      server:
        git:
          uri: ${GIT_CONFIG_SERVER_REPOSITORY_URI}
          search-paths:
            - test-service
            - treeflex-authorization-server
            - treeflex-email-service
            - treeflex-account-service
            - treeflex-service-dicovery-server
            - treeflex-api-gateway
            - treeflex-payment-gateway-service
          username: ${GIT_USERNAME}
          password: ${GIT_PASSWORD}
  profiles:
    active: ${APPLICATION_PROFILE}
server:
  port: ${APPLICATION_PORT}