version: '3.8'

services:
  config-server:
    image: rzdp97/treeflex-config-server:0.0.1-SNAPSHOT
    env_file:
      - treeflex-config-server/docker.env
    ports:
      - 8888:8888
    networks:
      - treeflex-microservices-network
  service-discovery-server:
    image: rzdp97/treeflex-service-discovery-server:0.0.1-SNAPSHOT
    env_file:
      - treeflex-service-discovery-server/docker.env
    ports:
      - 8761:8761
    networks:
      - treeflex-microservices-network
  authorization-server:
    image: rzdp97/treeflex-authorization-server:0.0.1-SNAPSHOT
    env_file:
      - treeflex-authorization-server/docker.env
    ports:
      - 8080:8080
    depends_on:
      - config-server
      - service-discovery-server
    networks:
      - treeflex-microservices-network
    restart: on-failure:10
  api-gateway:
    image: rzdp97/treeflex-api-gateway:0.0.1-SNAPSHOT
    env_file:
      - treeflex-api-gateway/docker.env
    ports:
      - 8765:8765
    depends_on:
      - config-server
      - service-discovery-server
      - authorization-server
    networks:
      - treeflex-microservices-network
    restart: on-failure:10
  zipkin-server:
    image: openzipkin/zipkin
    container_name: zipkin
    environment:
      - STORAGE_TYPE=mem
    ports:
      - 9411:9411
    depends_on:
      - email-service
      - account-service
      - api-gateway
    networks:
      - treeflex-microservices-network
    restart: on-failure:10
  email-service:
    image: rzdp97/treeflex-email-service:0.0.1-SNAPSHOT
    env_file:
      - treeflex-email-service/docker.env
    ports:
      - 8085:8085
    depends_on:
      - config-server
      - service-discovery-server
      - authorization-server
      - api-gateway
    networks:
      - treeflex-microservices-network
    restart: on-failure:10
  payment-gateway-service:
    image: rzdp97/treeflex-payment-gateway-service:0.0.1-SNAPSHOT
    env_file:
      - treeflex-payment-gateway-service/docker.env
    ports:
      - 8084:8084
    depends_on:
      - config-server
      - service-discovery-server
      - authorization-server
      - api-gateway
    networks:
      - treeflex-microservices-network
    restart: on-failure:10
  account-service:
    image: rzdp97/treeflex-account-service:0.0.1-SNAPSHOT
    env_file:
      - treeflex-account-service/docker.env
    ports:
      - 8081:8081
    depends_on:
      - config-server
      - service-discovery-server
      - authorization-server
      - email-service
      - payment-gateway-service
      - api-gateway
    networks:
      - treeflex-microservices-network
    restart: on-failure:10
networks:
  treeflex-microservices-network:
