version: '3.8'

services:
  config-server:
    image: rzdp97/treeflex-config-server:0.0.1-SNAPSHOT
    env_file:
      - treeflex-config-server/docker.env
    ports:
      - 8888:8888
    networks:
      - treeflex-microservices-network
  authorization-server:
    image: rzdp97/treeflex-authorization-server:0.0.1-SNAPSHOT
    env_file:
      - treeflex-authorization-server/docker.env
    ports:
      - 8080:8080
    depends_on:
      - config-server
    networks:
      - treeflex-microservices-network
    restart: on-failure:10
  email-service:
    image: rzdp97/treeflex-email-service:0.0.1-SNAPSHOT
    env_file:
      - treeflex-email-service/docker.env
    ports:
      - 8085:8085
    depends_on:
      - config-server
      - authorization-server
    networks:
      - treeflex-microservices-network
    restart: on-failure:10
  account-service:
    image: rzdp97/treeflex-account-service:0.0.1-SNAPSHOT
    env_file:
      - treeflex-account-service/docker.env
    ports:
    - 8081:8081
    depends_on:
      - config-server
      - authorization-server
      - email-service
    networks:
      - treeflex-microservices-network
    restart: on-failure:10

networks:
  treeflex-microservices-network:
