FROM openjdk:8-jdk-alpine
MAINTAINER Rriz
EXPOSE 8888
ADD target/treeflex-email-service-0.0.1-SNAPSHOT.jar treeflex-email-service-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "treeflex-email-service-0.0.1-SNAPSHOT.jar"]
