FROM openjdk:8-jdk-alpine
MAINTAINER Rriz
EXPOSE 8080
ADD target/treeflex-authorization-server-0.0.1-SNAPSHOT.jar treeflex-authorization-server-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "treeflex-authorization-server-0.0.1-SNAPSHOT.jar"]
