FROM openjdk:8-jdk-alpine
MAINTAINER Rriz
EXPOSE 8888
ADD target/treeflex-config-server-0.0.1-SNAPSHOT.jar treeflex-config-server-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "treeflex-config-server-0.0.1-SNAPSHOT.jar"]
