FROM openjdk:8-jdk-alpine
MAINTAINER Rriz
EXPOSE 8081
ADD target/treeflex-account-service-0.0.1-SNAPSHOT.jar treeflex-account-service-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "treeflex-account-service-0.0.1-SNAPSHOT.jar"]
