FROM openjdk:8-jdk-alpine
MAINTAINER Rriz
EXPOSE 8084
ADD target/treeflex-payment-gateway-service-0.0.1-SNAPSHOT.jar treeflex-payment-gateway-service-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "treeflex-payment-gateway-service-0.0.1-SNAPSHOT.jar"]
